### ISSUE TITLE
体验版进入首页报错

### ISSUE THREAD

**Issue by peakliuz** [GeekEra/GBlog-wx#11]
## halo环境信息
版本：1.4.11
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

## 体验版打开调试模式报错信息如下
![751634134466_ pic](https://user-images.githubusercontent.com/75781948/137158081-2affd8fc-38e1-46c6-8bd2-80d159f06874.jpg)

## 导入方式如下
![image](https://user-images.githubusercontent.com/75781948/137159018-73542b6f-c9a3-4127-a7ab-c8e1225c3d47.png)

**Comment by fuzui** [comment]
是否按照要求“将config中有个api-tmp.js文件重命名为api.js。”配置成功了呢。

**Comment by fuzui** [comment]
或者在开发者工具中一切正常吗

**Comment by peakliuz** [comment]
现在不报api.js找不到了,开发者工具里面的报错换了一个,另外文章海报分享这个链接好像不行了[开启文章分享海报功能](https://docs.geekera.cn/gblog-wx/posters-share.html)
![image](https://user-images.githubusercontent.com/75781948/137168700-b0b7b46b-a68c-401b-aa49-5b3d2582aa24.png)

**Comment by peakliuz** [comment]
halo环境已经升上去了还是不行,我是后端开发,前端实在看不懂
版本：1.4.12
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

**Comment by fuzui** [comment]
抱歉，这是前两天修改造成的bug，感谢提出。现已修改，请重新拉取下代码。
拉取后重新复制一份api.js进行修改。

**Comment by fuzui** [comment]
文档已更新：[GBlog-wx文档](https://docs.geekera.cn/gblog-wx/)
