### ISSUE TITLE
后台登录相关

### ISSUE THREAD

**Issue by IILee5** [GeekEra/GBlog-wx#8]
大佬后台管理能不能根据微信号来直接绑定呀，比如说，用户使用微信登录了，获取到用户的微信id，然后如果是后台配置的微信ID，可以直接免登录(自动登录)进入后台。

**Comment by fuzui** [comment]
直接绑定不灵活。比如我有两个微信。并且这样微信的openid、用户名、密码需要写死了，你说的“后台配置的微信ID”，后台管理界面不存在该配置，最简单是写在配置文件里。改一次密码就需要改一次配置重新提交审核。且使用之前还需要单独去获取openid。当然也可以使用云函数。
后面会考虑使用云函数来优化这块。在首次登陆后，将openid与加密后的用户名密码存放在小程序云库上，加密盐存放于配置文件中。后续再使用该微信时，便可跳过输入用户名密码。

**Comment by IILee5** [comment]
![image](https://user-images.githubusercontent.com/40862062/122712666-dc6d2580-d296-11eb-8ba9-ef529fb28996.png)
您好，在开发中选项里面有可以直接调用的静态变量，可以尝试从这个方面入手，可以有多个openid。不过感觉您用小程序云库的方式也很可以实现:)

**Comment by fuzui** [comment]
采用后台配置变量的方式还有其他问题，例如账号密码的灵活性、部署使用的便捷性。综合考虑还是会使用小程序云函数方式，虽然增加了云函数的配置，但却是一次性的配置，后期密码修改、新微信增加、部署均不会与此挂钩。
目前在重写首页、分类、图库、评论的页面，该功能开发需排在此之后。

**Comment by IILee5** [comment]
好的，感谢大佬，目前小程序正在使用您这一套代码在跑，ui跟使用上的便捷性都特别好~

**Comment by fuzui** [comment]
已完成。[后台免密登陆](https://docs.geekera.cn/gblog-wx/nosercet-login.html)
